version: '3.8'
services:
  saludo-service:
    build: ./saludo-service
    ports:
      - "3000:3000"

  cliente-service:
    build: ./cliente-service
    ports:
      - "4000:4000"
    depends_on:
      - saludo-service
